### ISSUE TITLE
g_object_new_is_valid_property: property 'name' for type 'GstRtpL16Pay' cannot be set twice

### ISSUE THREAD

**Issue by moskovskiy82** [thirtythreeforty/neolink#353]
](neolink:7): GLib-GObject-CRITICAL **: 14:43:00.195: g_object_new_is_valid_property: property 'name' for type 'GstRtpL16Pay' cannot be set twice)

After upgrading to Reolink B800 Firmware to the latest on their website v 3.0.0.183 from vanilla v 3.0.0 got the following error

[2023-04-23T14:46:13Z INFO  neolink::rtsp] Main: Starting video stream Main Stream (Clear)
(neolink:7): GLib-GObject-CRITICAL **: 14:46:20.457: g_object_new_is_valid_property: property 'name' for type 'GstRtpL16Pay' cannot be set twice
(neolink:7): GStreamer-CRITICAL **: 14:46:22.207: gst_buffer_n_memory: assertion 'GST_IS_BUFFER (buffer)' failed
(neolink:7): GStreamer-CRITICAL **: 14:46:22.207: gst_mini_object_lock: assertion 'GST_MINI_OBJECT_IS_LOCKABLE (object)' failed
Segmentation fault (core dumped)

**Comment by zimmra** [comment]
I am getting the same error when trying to access the stream of my Lumus (fw. ver. v2.0.0.705_21052800)
```log
2023-05-01T15:13:05.954779505Z (neolink:6): GLib-GObject-CRITICAL **: 15:13:05.954: g_object_new_is_valid_property: property 'name' for type 'GstRtpL16Pay' cannot be set twice
```

**Comment by QuantumEntangledAndy** [comment]
This is fixed in my fork. Please see there for updates this fork is mostly unmaintained

**Comment by rockas69** [comment]
Still have this error. Setting up for Reolink E1 Pro cameras.

`(neolink:8): GLib-GObject-CRITICAL **: 08:45:19.188: g_object_new_is_valid_property: property 'name' for type 'GstRtpL16Pay' cannot be set twice`

**Comment by QuantumEntangledAndy** [comment]
What version are you currently on. Should work fine if your using the one from my fork. As far as I'm aware there's no one actively maintaining this fork any more. If you are using mine please open the issue there.

**Comment by BloodBlight** [comment]
I am also seeing this.  Though I cannot use subStream, my camera doesn't seem to like that (have it in "both" at the moment for testing, but seems to be just as both or worse).

I am using docker and appear to have the latest image, though it is 3 months old:
```thirtythreeforty/neolink      latest       7f8a856bc6f3   3 months ago    155MB```

The stream works for a few minutes, then crashes.  I thought it was just the camera over heating or something, so I have it turn off for a bit every night, but that hasn't helped.  So not sure what the deal is.

```
[2023-08-20T15:33:23Z INFO  neolink] Neolink 0.4.0 (unknown commit) release
[2023-08-20T15:33:33Z WARN  neolink::rtsp] The format config option of the camera has been removed in favour of auto detection.
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Connecting to camera at Address: 192.###.###.###:9000
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Logging in
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Connecting to camera at Address: 192.###.###.###:9000
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Logging in
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Connected and logged in
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Connected and logged in
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Starting video stream Sub Stream (Fluent)
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Camera time is already set: 2023-08-20 8:33:33 -8
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Camera reports firmware version v2.0.0.705_21052800
[2023-08-20T15:33:33Z INFO  neolink::rtsp] WiFi1: Starting video stream Main Stream (Clear)

(neolink:7): GLib-GObject-CRITICAL **: 15:33:42.546: g_object_new_is_valid_property: property 'name' for type 'GstRtpL16Pay' cannot be set twice
Segmentation fault (core dumped)
```

My config:
```
bind = "0.0.0.0"

[[cameras]]
name = "WiFi1"
username = "#########"
password = "#########"
address = "192.###.###.###:9000"
format = "H264"
stream = "both"
```

**Comment by QuantumEntangledAndy** [comment]
@BloodBlight this fork is unmaintained. Please read the sticked issue about that and swap to my fork.

**Comment by BloodBlight** [comment]
Oh, thank you!   I hope @thirtythreeforty is okay!

I appreciate the work and the link!
